name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install tox, tox-gh-actions, and build tools
        run: pip install tox tox-gh-actions build

      - name: Upgrade pip and install build dependency
        run: python -m pip install --upgrade pip build

      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Restore mypy cache
        id: cache-mypy-restore
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-py${{ matrix.python-versions }}-mypy-${{ hashFiles('**/.mypy_cache/**') }}

      - name: Run tests using Makefile
        run: make tests

      - name: Save mypy cache
        id: cache-mypy-save
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-py${{ matrix.python-versions }}-mypy-${{ hashFiles('**/.mypy_cache/**') }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: false
          verbose: true
